
import type { Metadata } from "next";
import Script from "next/script";
import "prismjs/themes/prism-okaidia.css";
import "prismjs/plugins/line-numbers/prism-line-numbers.css";
import "./globals.css";

import { ThemeProvider } from "@/components/ui/theme-provider";
import { AnimationsProvider } from "@/context";
import ClientWrapper from "@/components/ClientWrapper";
import NavBar from "@/components/NavBar";
import ClickSound from "@/components/ui/ClickSound";

export const metadata: Metadata = {
  title: "Shubham Nayak | Portfolio",
  description: "Explore my projects, designs, and work by Shubham Nayak.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/*   Font preload for SF Pro */}
        <link
          rel="preload"
          href="/fonts/sf-pro/SFPRODISPLAYBOLD.OTF"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/sf-pro/SFPRODISPLAYMEDIUM.OTF"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/sf-pro/SFPRODISPLAYREGULAR.OTF"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
        <meta name="theme-color" content="#e1dfdd" />
      </head>

      <body className="antialiased">
        {/*   Smooth scroll polyfill */}
        <Script
          id="smooth-scroll-polyfill"
          strategy="afterInteractive"
          src="https://polyfill.io/v3/polyfill.min.js?features=smoothscroll"
        />

        {/*   Context and Theme Setup */}
        <AnimationsProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ClientWrapper>
              <NavBar />
              <ClickSound />

              {children}
            </ClientWrapper>
          </ThemeProvider>
        </AnimationsProvider>

        {/* Modal portal */}
        <div id="modal-root" />
      </body>
    </html>
  );
}






















// import type { Metadata } from "next";
// import "./globals.css";
// import { ThemeProvider } from "../components/ui/theme-provider";
// import NavBar from "@/components/NavBar";

// export const metadata: Metadata = {
//   title: "Shubham Nayak",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body>
//         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
//           <NavBar />
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }